### ISSUE TITLE
`Individuals:` anonymous individuals in Manchester syntax

### ISSUE THREAD

**Issue by b-gehrke** [owlcs/owlapi#1006]
When loading an ontology which contains anonymous individuals and rendering it to functional syntax or manchester syntax the nodeIds of those individuals get replaced by `_:genid<someNumber>`. Why aren't the original nodeIds kept?

Furthermore, rendering in manchester Syntax introduces an `Individuals:` "axiom" (see example below). The [standard](https://www.w3.org/TR/owl2-manchester-syntax) doesn't define it. What does it mean and why is it used?

Example (taken from [bioportal/BRIDG.owl](https://ontohub.org/bioportal/BRIDG.owl))
```
<?xml version="1.0" encoding="UTF-8"?>
<owl:Ontology xmlns:owl="http://www.w3.org/2002/07/owl#">
  <owl:Prefix name="foaf" IRI="http://xmlns.com/foaf/0.1/"/>
  <owl:ClassAssertion>
    <owl:Class abbreviatedIRI="foaf:Organization"/>
    <owl:AnonymousIndividual nodeID="SCC"/>
  </owl:ClassAssertion>
  <owl:ClassAssertion>
    <owl:Class abbreviatedIRI="foaf:Organization"/>
    <owl:AnonymousIndividual nodeID="CDISC"/>
  </owl:ClassAssertion>
</owl:Ontology>
```

Rendered in manchester syntax
```
Prefix: owl: <http://www.w3.org/2002/07/owl#>
Prefix: rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
Prefix: rdfs: <http://www.w3.org/2000/01/rdf-schema#>
Prefix: xml: <http://www.w3.org/XML/1998/namespace>
Prefix: xsd: <http://www.w3.org/2001/XMLSchema#>

Ontology: 
Class: <http://xmlns.com/foaf/0.1/Organization>
    Individuals: 
        _:genid2147483648,
        _:genid2147483649
Individual: _:genid2147483648
    Types: 
        <http://xmlns.com/foaf/0.1/Organization>
Individual: _:genid2147483649
    Types: 
        <http://xmlns.com/foaf/0.1/Organization>
```

Rendered in functional syntax
```
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(foaf:=<http://xmlns.com/foaf/0.1/>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)

Ontology(
Declaration(Class(foaf:Organization))

ClassAssertion(foaf:Organization _:genid2147483648)
ClassAssertion(foaf:Organization _:genid2147483649)
)
```
