### ISSUE TITLE
Manchester syntax parser crashes on class/property punning

### ISSUE THREAD

**Issue by cmungall** [owlcs/owlapi#851]
Note that there was a similar issue fixed in #548 but there wasn't a test case, so this seems to be a new case.

The following ontology puns `creator_of`, but it is impossible to use the punned OP in a HasValue expression:

```
Prefix: : <http://x.org/>

Ontology: <http://x.org>
## comment to prevent interpretation as obo format

Individual: x
Class: creator_of
ObjectProperty: creator_of

Class: Test
  EquivalentClasses: creator_of value x
```

yields

```
Encountered value at line 11 column 32. Expected one of:
        Individual:
        AnnotationProperty:
        or
        Datatype:
        DataProperty:
        ObjectProperty:
        DisjointProperties:
        ,
        ValuePartition:
        EquivalentClasses:
        Import:
        Prefix:
        DisjointClasses:
        and
        Class:
        SameIndividual:
        DifferentIndividuals:
        org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl$ExceptionBuilder.build(Manchester
OWLSyntaxParserImpl.java:2521)
```
